### PR TITLE
provide a schema file at runtime; post a schema definition to the server

### LINKED ISSUE #152: Schema request in Python client
Need a method to retrieve schema in python client.

### LINKED ISSUE #176: Less verbose schema
Because GRIP is trying to identify every key found in the expression data, the schema dump is over 8MB. Most of those details aren't useful for seeing the overall graph. We need a much less verbose description of the graph.

### PR DESCRIPTION
**Pull request by adamstruck**
closes #152 
closes #176

### CODE REVIEW

**Comment by kellrott** [comment]
Can we add the inference code as a tool that can be called on data files?

**Comment by adamstruck** [comment]
Building the schema from the data files will take some work. I suggest we add that tool in a future PR.

**Comment by kellrott** [comment]
Added #179 to implement requested behavior.

**Comment by kellrott** [comment]
The graph list includes the schema, those should probably be filtered out.

```
grip list
```
returns
```
example-graph
example-graph__schema__
```

**Comment by adamstruck** [comment]
The graph list intentionally includes the schema. Schemas are themselves graphs that can be traversed.

**Pull request merged**
